trigger:
- develop

pool: Default

steps:
- checkout: self
  submodules: true
  persistCredentials: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      F:\tool\vcpkg\vcpkg.exe install gtest:x64-windows
- task: CMake@1
  inputs:
    cmakeArgs: '.. -DUSE_DIRECTX=ON -DCMAKE_TOOLCHAIN_FILE="F:/tool/vcpkg/scripts/buildsystems/vcpkg.cmake"'
- task: CMake@1
  inputs:
    cmakeArgs: '--build . -j'